SELECT  ROUND(AVG(O.TOTALPRICE),0) FROM ORDERS O
HAVING AVG(O.TOTALPRICE)>
  (
  SELECT ROUND(SUM(O2.TOTALPRICE),0) TOPLAM_SATIS FROM USERS U
  JOIN ORDERS O2 ON O2.USERID=U.ID
  GROUP BY U.NAMESURNAME,U.ID
  )
