-- =====================================================
-- Query: City Sales Percentage
-- Description: This query calculates the total sales generated by each city and shows 
-- the percentage contribution of each city to overall sales.
-- Tables Used: ORDERS, ADDRESS, CITIES
-- =====================================================

SELECT T.CityID, T.TotalSalesCity, 
(T.TotalSalesCity 
  / 
(SELECT SUM(T.TotalSalesCity) FROM
	(
  	SELECT C.ID AS CityID, SUM(O.TOTALPRICE) AS TotalSalesCity FROM ORDERS O 
  	JOIN ADDRESS A ON A.ID=O.ADDRESSID
  	JOIN CITIES C ON C.ID=A.CITYID
  	GROUP BY C.ID
	) AS T
) *100) AS SalesPercentage
FROM
(
  SELECT C.ID AS CityID, SUM(O.TOTALPRICE) AS TotalSalesCity FROM ORDERS O 
  JOIN ADDRESS A ON A.ID=O.ADDRESSID
  JOIN CITIES C ON C.ID=A.CITYID
  GROUP BY C.ID
) AS T
WHERE 
(T.TotalSalesCity / 
(SELECT SUM(T.TotalSalesCity) FROM
	(
  	SELECT C.ID AS CityID, SUM(O.TOTALPRICE) AS TotalSalesCity FROM ORDERS O 
  	JOIN ADDRESS A ON A.ID=O.ADDRESSID
  	JOIN CITIES C ON C.ID=A.CITYID
  	GROUP BY C.ID
	) AS T
) *100)>5
ORDER BY T.CityID
