-- =====================================================
-- Query: City Sales Percentage
-- Description: This query calculates the total sales generated by each city and shows 
-- the percentage contribution of each city to overall sales.
-- Tables Used: ORDERS, ADDRESS, CITIES
-- =====================================================

SELECT T.CityID, T.CityName, T.TotalSales, 
(T.TotalSales 
  / 
(SELECT SUM(X.TotalSales) FROM
	(
  	SELECT C.ID AS CityID, C.CITY AS CityName, SUM(O.TOTALPRICE) AS TotalSales FROM ORDERS O 
  	JOIN ADDRESS A ON A.ID=O.ADDRESSID
  	JOIN CITIES C ON C.ID=A.CITYID
  	GROUP BY C.ID, C.CITY
	) AS X
) *100) AS SalesPercentage
FROM
(
  SELECT C.ID AS CityID, C.CITY AS CityName, SUM(O.TOTALPRICE) AS TotalSales FROM ORDERS O 
  JOIN ADDRESS A ON A.ID=O.ADDRESSID
  JOIN CITIES C ON C.ID=A.CITYID
  GROUP BY C.ID, C.CITY
) AS T
WHERE 
(T.TotalSales / 
(SELECT SUM(X.TotalSales) FROM
	(
  	SELECT C.ID AS CityID, C.CITY AS CityName, SUM(O.TOTALPRICE) AS TotalSales FROM ORDERS O 
  	JOIN ADDRESS A ON A.ID=O.ADDRESSID
  	JOIN CITIES C ON C.ID=A.CITYID
  	GROUP BY C.ID, C.CITY
	) AS X
) *100)>5
ORDER BY T.CityID
